### ISSUE TITLE
Webpage is not loading

### ISSUE THREAD

**Issue by bojidartonchev** [ayushswiss/EdgeBrowserByAyush#1]
Hello,

First thanks for the great work you have done here.

I compiled your project as is, but the page is not rendered. I am using Webview2 Runtime v88.0.705.56 x64

This is the result:
![image](https://user-images.githubusercontent.com/12398245/106454857-0bbff900-6494-11eb-89bc-47ba462bd6d7.png)

Do you have any idea what may cause this behavior?

Best regards!

**Comment by ayushswiss** [comment]
Something has been changed in the WebView2 installation. It's not the latest package in Visual Studio. Maybe they revoke any method or something.

Now it's the same for me. I need to investigate further for the solution over the weekend. But it was working.

**Comment by ayushswiss** [comment]
Hello Bojidar,

Thanks for reporting the issue, As I was suspected and mentioned in the last comment that maybe Microsoft revoked the library was true.

Previously the project was built on the WebView2-Prerelease package, and now Microsoft revoked that version. And now I upgraded the project to a newer build. Now I tested it and it's working fine again.

Thanks again.

**Comment by bojidartonchev** [comment]
I can confirm everything is working fine now.

Thanks.

**Comment by ayushswiss** [comment]
Great, thank you so much.
